# Generated by Django 5.0.6 on 2024-06-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
                ('companyid', models.CharField(max_length=20, unique=True)),
                ('contactperson_name', models.CharField(max_length=100)),
                ('contactemail', models.EmailField(max_length=254)),
                ('contactphonenumber', models.CharField(max_length=20)),
                ('companyaddressstreet', models.CharField(max_length=255)),
                ('companyaddresscity', models.CharField(max_length=100)),
                ('companyaddressstate', models.CharField(max_length=100)),
                ('companyaddresspostalcode', models.CharField(max_length=20)),
                ('companyaddresscountry', models.CharField(max_length=100)),
                ('companytype', models.CharField(max_length=50)),
                ('companyregistrationnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('companytaxidentificationnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('companyindustrytype', models.CharField(max_length=100)),
                ('companydateofestablishment', models.DateField()),
                ('companynumberofemployees', models.IntegerField()),
                ('companybusinesshours', models.CharField(max_length=100)),
                ('companywebsiteurl', models.URLField(blank=True, null=True)),
                ('companyfacebookurl', models.URLField(blank=True, null=True)),
                ('companytwitterurl', models.URLField(blank=True, null=True)),
                ('companylinkedinurl', models.URLField(blank=True, null=True)),
                ('companyinstagramurl', models.URLField(blank=True, null=True)),
                ('companylogoimage', models.ImageField(blank=True, null=True, upload_to='shop/images')),
                ('companyadditionalnotes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
