# Generated by Django 5.0.6 on 2024-07-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='condition',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactivate', 'Deactivate')], default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
